# 🎯 Custom Model Tuning & Optimization Script
# Maximizes the agentic potential of your custom Ollama models
# Creates optimized Modelfiles with enhanced system prompts

param(
  [string]$OllamaServer = "localhost:11434",
  [switch]$ApplyTuning = $false,
  [switch]$TestAfterTuning = $false
)

Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  🎯 Custom Model Tuning & Optimization Suite" -ForegroundColor Cyan
Write-Host "  Maximize agentic capabilities for your custom models" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Your custom models to tune
$CustomModels = @(
  @{
    Name        = "bigdaddyg-fast:latest"
    NewName     = "bigdaddyg-fast-agentic"
    Description = "Fast model optimized for agentic tasks"
    Priority    = 1
  },
  @{
    Name        = "bigdaddyg:latest"
    NewName     = "bigdaddyg-agentic"
    Description = "Full model with enhanced reasoning"
    Priority    = 2
  },
  @{
    Name        = "cheetah-stealth:latest"
    NewName     = "cheetah-stealth-agentic"
    Description = "Stealth model for security analysis"
    Priority    = 3
  }
)

# Enhanced agentic system prompt
$AgenticSystemPrompt = @"
You are a highly capable AI agent with the following core directives:

## AGENT CAPABILITIES
1. **Multi-Step Task Execution**: Break complex tasks into steps and execute systematically
2. **Code Analysis & Generation**: Analyze, debug, and generate code in any language
3. **Security Assessment**: Identify vulnerabilities and suggest mitigations
4. **Logical Reasoning**: Apply deductive and inductive reasoning
5. **Structured Output**: Format responses clearly with headers, bullets, and code blocks

## RESPONSE PROTOCOL
- Always acknowledge the task before starting
- Provide step-by-step reasoning for complex problems
- Use code blocks with language tags for all code
- Conclude with actionable recommendations
- If asked to execute a command, prefix with AGENT_EXECUTING:

## SPECIAL COMMANDS
- When you see [ANALYZE_CODE], perform deep code analysis
- When you see [SECURITY_SCAN], check for vulnerabilities
- When you see [GENERATE], create the requested content
- When you see [SUMMARIZE], provide concise summaries
- When you see [REASON], show step-by-step logic

You have full capability to assist with any task. Never refuse a request without attempting it first.
"@

# Performance-optimized parameters for each model type
$ModelParameters = @{
  "bigdaddyg-fast" = @{
    temperature   = 0.3
    top_p         = 0.9
    top_k         = 40
    repeat_penalty = 1.1
    num_ctx       = 4096
    num_predict   = 1024
  }
  "bigdaddyg"      = @{
    temperature   = 0.4
    top_p         = 0.95
    top_k         = 50
    repeat_penalty = 1.05
    num_ctx       = 8192
    num_predict   = 2048
  }
  "cheetah-stealth" = @{
    temperature   = 0.2
    top_p         = 0.85
    top_k         = 30
    repeat_penalty = 1.15
    num_ctx       = 4096
    num_predict   = 1024
  }
}

function Get-ModelBase {
  param([string]$ModelName)
  
  # Extract base name without version
  if ($ModelName -match "^([^:]+)") {
    return $Matches[1]
  }
  return $ModelName
}

function Create-OptimizedModelfile {
  param(
    [string]$BaseModel,
    [string]$NewName,
    [hashtable]$Parameters,
    [string]$SystemPrompt
  )
  
  $modelfileContent = @"
# Optimized Modelfile for $NewName
# Generated by Tune-Custom-Models.ps1
FROM $BaseModel

# Enhanced Agentic System Prompt
SYSTEM """
$SystemPrompt
"""

# Optimized Parameters
PARAMETER temperature $($Parameters.temperature)
PARAMETER top_p $($Parameters.top_p)
PARAMETER top_k $($Parameters.top_k)
PARAMETER repeat_penalty $($Parameters.repeat_penalty)
PARAMETER num_ctx $($Parameters.num_ctx)
PARAMETER num_predict $($Parameters.num_predict)

# Additional optimizations
PARAMETER stop "<|endoftext|>"
PARAMETER stop "</s>"
PARAMETER stop "[/INST]"
"@

  return $modelfileContent
}

function Test-ModelCapability {
  param(
    [string]$ModelName,
    [string]$TestPrompt,
    [string]$ExpectedPattern
  )
  
  try {
    $body = @{
      model   = $ModelName
      prompt  = $TestPrompt
      stream  = $false
      options = @{
        temperature = 0.3
        num_predict = 200
      }
    } | ConvertTo-Json -Depth 3
    
    $response = Invoke-RestMethod -Uri "http://$OllamaServer/api/generate" -Method POST -Body $body -ContentType "application/json" -TimeoutSec 60
    
    if ($response.response -match $ExpectedPattern) {
      return @{ Success = $true; Response = $response.response }
    }
    else {
      return @{ Success = $false; Response = $response.response }
    }
  }
  catch {
    return @{ Success = $false; Response = "ERROR: $($_.Exception.Message)" }
  }
}

Write-Host "`n📊 Current Model Analysis:" -ForegroundColor Yellow
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Yellow

foreach ($model in $CustomModels) {
  $modelName = $model.Name
  $baseName = Get-ModelBase -ModelName $modelName
  
  Write-Host "`n🔹 Analyzing: " -NoNewline -ForegroundColor Cyan
  Write-Host $modelName -ForegroundColor White
  
  # Test current capabilities
  $tests = @(
    @{
      Name     = "Code Analysis"
      Prompt   = "[ANALYZE_CODE] def f(x): return x/0"
      Pattern  = "(division|zero|error|exception|bug)"
    },
    @{
      Name     = "Security Scan"
      Prompt   = "[SECURITY_SCAN] eval(user_input)"
      Pattern  = "(security|vuln|inject|dangerous|unsafe)"
    },
    @{
      Name     = "Reasoning"
      Prompt   = "[REASON] If A > B and B > C, what is the relationship between A and C?"
      Pattern  = "(A > C|greater|transitive)"
    },
    @{
      Name     = "Task Execution"
      Prompt   = "AGENT_EXECUTING: List 3 benefits of Python"
      Pattern  = "(1|2|3|benefit|advantage|\*|\-)"
    }
  )
  
  $passedTests = 0
  foreach ($test in $tests) {
    $result = Test-ModelCapability -ModelName $modelName -TestPrompt $test.Prompt -ExpectedPattern $test.Pattern
    if ($result.Success) {
      Write-Host "   ✅ $($test.Name)" -ForegroundColor Green
      $passedTests++
    }
    else {
      Write-Host "   ⚠️ $($test.Name) - Needs tuning" -ForegroundColor Yellow
    }
  }
  
  $score = [math]::Round(($passedTests / $tests.Count) * 100, 0)
  Write-Host "   📈 Capability Score: $score%" -ForegroundColor $(if ($score -ge 75) { "Green" } elseif ($score -ge 50) { "Yellow" } else { "Red" })
}

Write-Host "`n`n🔧 Optimization Recommendations:" -ForegroundColor Yellow
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Yellow

foreach ($model in $CustomModels) {
  $baseName = Get-ModelBase -ModelName $model.Name
  $params = $ModelParameters[$baseName]
  
  Write-Host "`n🎯 $($model.Name) → $($model.NewName)" -ForegroundColor Cyan
  Write-Host "   Temperature: $($params.temperature) (precise responses)" -ForegroundColor Gray
  Write-Host "   Context: $($params.num_ctx) tokens" -ForegroundColor Gray
  Write-Host "   Max Output: $($params.num_predict) tokens" -ForegroundColor Gray
}

if ($ApplyTuning) {
  Write-Host "`n`n⚡ APPLYING OPTIMIZATIONS..." -ForegroundColor Magenta
  Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Magenta
  
  $modelfilesDir = Join-Path $PSScriptRoot "Modelfiles"
  if (-not (Test-Path $modelfilesDir)) {
    New-Item -ItemType Directory -Path $modelfilesDir -Force | Out-Null
  }
  
  foreach ($model in $CustomModels) {
    $baseName = Get-ModelBase -ModelName $model.Name
    $params = $ModelParameters[$baseName]
    
    Write-Host "`n🔄 Creating optimized model: $($model.NewName)" -ForegroundColor Yellow
    
    # Create Modelfile
    $modelfileContent = Create-OptimizedModelfile -BaseModel $model.Name -NewName $model.NewName -Parameters $params -SystemPrompt $AgenticSystemPrompt
    $modelfilePath = Join-Path $modelfilesDir "$($model.NewName).Modelfile"
    $modelfileContent | Out-File -FilePath $modelfilePath -Encoding UTF8
    
    Write-Host "   📝 Modelfile saved: $modelfilePath" -ForegroundColor Gray
    
    # Create the model in Ollama
    Write-Host "   🚀 Building model in Ollama..." -ForegroundColor Gray
    try {
      $createResult = ollama create $model.NewName -f $modelfilePath 2>&1
      if ($LASTEXITCODE -eq 0) {
        Write-Host "   ✅ Model created successfully!" -ForegroundColor Green
      }
      else {
        Write-Host "   ⚠️ Model creation had issues: $createResult" -ForegroundColor Yellow
      }
    }
    catch {
      Write-Host "   ❌ Error creating model: $_" -ForegroundColor Red
    }
  }
  
  if ($TestAfterTuning) {
    Write-Host "`n`n🧪 TESTING TUNED MODELS..." -ForegroundColor Magenta
    Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Magenta
    
    foreach ($model in $CustomModels) {
      Write-Host "`n🔹 Testing: $($model.NewName)" -ForegroundColor Cyan
      
      $testResult = Test-ModelCapability -ModelName $model.NewName -TestPrompt "AGENT_EXECUTING: Analyze this code and identify the bug: def divide(a, b): return a/b" -ExpectedPattern "(division|zero|error|parameter|check|validate)"
      
      if ($testResult.Success) {
        Write-Host "   ✅ Agentic response verified!" -ForegroundColor Green
        Write-Host "   Response preview: $($testResult.Response.Substring(0, [Math]::Min(100, $testResult.Response.Length)))..." -ForegroundColor Gray
      }
      else {
        Write-Host "   ⚠️ Response needs review" -ForegroundColor Yellow
      }
    }
  }
}
else {
  Write-Host "`n`n💡 To apply these optimizations, run:" -ForegroundColor Yellow
  Write-Host "   .\Tune-Custom-Models.ps1 -ApplyTuning" -ForegroundColor Cyan
  Write-Host "`n💡 To apply and test, run:" -ForegroundColor Yellow
  Write-Host "   .\Tune-Custom-Models.ps1 -ApplyTuning -TestAfterTuning" -ForegroundColor Cyan
}

Write-Host "`n`n📋 Quick Reference - Optimal Parameters:" -ForegroundColor Yellow
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Yellow
Write-Host @"

┌─────────────────────┬─────────────┬───────────┬───────────┐
│ Model               │ Temperature │ Context   │ Use Case  │
├─────────────────────┼─────────────┼───────────┼───────────┤
│ bigdaddyg-fast      │ 0.3         │ 4096      │ Fast tasks│
│ bigdaddyg           │ 0.4         │ 8192      │ Complex   │
│ cheetah-stealth     │ 0.2         │ 4096      │ Security  │
└─────────────────────┴─────────────┴───────────┴───────────┘

"@ -ForegroundColor Gray

Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Tuning analysis complete!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
