#include "llm.h"
#include <algorithm>
#include <vector>

// A "Mini LLM" that mimics the behavior of the ASM Bot Swarm locally.
// It uses keyword detection to trigger "generative" tasks.

namespace TinyHome::LLM {

    std::string generate_asm_parser(bool large) {
        if (large) {
            return R"(// Generated by TinyHome Mini-LLM (ASM Bot Swarm Node)
// Mode: Enterprise / Large
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <algorithm>
#include <fstream>
#include <sstream>

class ASMParser {
    // ... (Full Enterprise Implementation would go here) ...
public:
    void parse() { std::cout << "Parsing complex ASM..." << std::endl; }
};
)";
        } else {
            return R"(// Generated by TinyHome Mini-LLM (ASM Bot Swarm Node)
// Mode: Standard
#include <iostream>
#include <vector>
#include <string>

class ASMParser {
public:
    void parse(std::string line) {
        // Simple parsing logic
        std::cout << "Parsing: " << line << std::endl;
    }
};
)";
        }
    }

    std::string process(const std::string& input) {
        std::string query = input;
        std::transform(query.begin(), query.end(), query.begin(), ::tolower);

        if (query.find("asm") != std::string::npos && query.find("parser") != std::string::npos) {
            bool large = (query.find("large") != std::string::npos || query.find("enterprise") != std::string::npos);
            return generate_asm_parser(large);
        }
        
        if (query.find("hello") != std::string::npos) {
            return "Greetings. I am the TinyHome Mini-LLM. I can generate ASM parsers. Try asking: 'Write me an ASM parser'.";
        }

        return "I am a specialized ASM Bot Swarm node. I didn't understand that request. Try asking for an ASM parser.";
    }
}
